[kitty-icon]
src.github_tag = "DinkDonk/kitty-icon"
fetch.github   = "DinkDonk/kitty-icon"

# Skills
[ai-coding-principles]
src.git      = "https://github.com/shelken/ai-coding-principles"
src.branch   = "main"
fetch.github = "shelken/ai-coding-principles"

[ast-grep-agent-skill]
src.git      = "https://github.com/ast-grep/agent-skill"
src.branch   = "main"
fetch.github = "ast-grep/agent-skill"

[cursor-plugins]
src.git      = "https://github.com/cursor/plugins"
src.branch   = "main"
fetch.github = "cursor/plugins"

[andrej-karpathy-skills]
src.git      = "https://github.com/forrestchang/andrej-karpathy-skills"
src.branch   = "main"
fetch.github = "forrestchang/andrej-karpathy-skills"

[anti-slop]
src.github_tag = "dmmulroy/anti-slop"
fetch.github   = "dmmulroy/anti-slop"

[humanlayer-skills]
src.git      = "https://github.com/humanlayer/skills"
src.branch   = "main"
fetch.github = "humanlayer/skills"

[llamaparse-agent-skills]
src.github_tag    = "run-llama/llamaparse-agent-skills"
src.include_regex = "liteparse-.*"
fetch.github      = "run-llama/llamaparse-agent-skills"

[mattpocock-skills]
src.github_tag = "mattpocock/skills"
fetch.github   = "mattpocock/skills"

[reverse-skill]
src.github_tag = "zhaoxuya520/reverse-skill"
fetch.github   = "zhaoxuya520/reverse-skill"

# Tools & Plugins
[zjstatus]
src.github = "dj95/zjstatus"
fetch.url  = "https://github.com/dj95/zjstatus/releases/download/$ver/zjstatus.wasm"

[yazi-plugins]
src.git      = "https://github.com/yazi-rs/plugins"
src.branch   = "main"
fetch.github = "yazi-rs/plugins"

[projects-yazi]
src.git      = "https://github.com/MasouShizuka/projects.yazi"
src.branch   = "main"
fetch.github = "MasouShizuka/projects.yazi"
