# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ai-coding-principles = {
    pname = "ai-coding-principles";
    version = "27db986fd2790ad1a1818a7f1b2c5d91b3843b8e";
    src = fetchFromGitHub {
      owner = "shelken";
      repo = "ai-coding-principles";
      rev = "27db986fd2790ad1a1818a7f1b2c5d91b3843b8e";
      fetchSubmodules = false;
      sha256 = "sha256-fkaO77jOmg9q3jEZe64SWgNWb2PUX9C1KvRDg4H+w8Y=";
    };
    date = "2026-03-26";
  };
  andrej-karpathy-skills = {
    pname = "andrej-karpathy-skills";
    version = "2c606141936f1eeef17fa3043a72095b4765b9c2";
    src = fetchFromGitHub {
      owner = "forrestchang";
      repo = "andrej-karpathy-skills";
      rev = "2c606141936f1eeef17fa3043a72095b4765b9c2";
      fetchSubmodules = false;
      sha256 = "sha256-4z/wRdYH7UXRzF8RJU0sw8xbpx0BW/7CBv5sVEC2knY=";
    };
    date = "2026-04-20";
  };
  hindsight-skills = {
    pname = "hindsight-skills";
    version = "89c34c31357ecd80e2ab2ed3244d9e37515cb5f8";
    src = fetchFromGitHub {
      owner = "vectorize-io";
      repo = "hindsight";
      rev = "89c34c31357ecd80e2ab2ed3244d9e37515cb5f8";
      fetchSubmodules = false;
      sha256 = "sha256-pFeZzsNyNDxjpbNq/913nRXVlMIatiMUU6qp70uiypE=";
    };
    date = "2026-04-29";
  };
  kitty-icon = {
    pname = "kitty-icon";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "DinkDonk";
      repo = "kitty-icon";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-q5wNdFRMvQDx3DlO7zdy/xPJbqcNlm4iVKaBwjxlSMs=";
    };
  };
  llamaparse-agent-skills = {
    pname = "llamaparse-agent-skills";
    version = "1f10f60a9eba0dbb490724c8104b0a865365f136";
    src = fetchFromGitHub {
      owner = "run-llama";
      repo = "llamaparse-agent-skills";
      rev = "1f10f60a9eba0dbb490724c8104b0a865365f136";
      fetchSubmodules = false;
      sha256 = "sha256-+YVBjEiUYlMc+2jlBLDCEbg6Qn1dgHgTpI8j9lnOseQ=";
    };
    date = "2026-03-03";
  };
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "b843cb5ea74b1fe5e58a0fc23cddef9e66076fb8";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "b843cb5ea74b1fe5e58a0fc23cddef9e66076fb8";
      fetchSubmodules = false;
      sha256 = "sha256-qOhU5bBnT6kI8c7i0r0IyecrgLJNNPlmQtAb6qWM73Q=";
    };
    date = "2026-04-30";
  };
  obra-superpowers = {
    pname = "obra-superpowers";
    version = "6efe32c9e2dd002d0c394e861e0529675d1ab32e";
    src = fetchFromGitHub {
      owner = "obra";
      repo = "superpowers";
      rev = "6efe32c9e2dd002d0c394e861e0529675d1ab32e";
      fetchSubmodules = false;
      sha256 = "sha256-0WupTacT1jIwVBloj1i0RF7wIllVtP8eMPRl7VrXdbE=";
    };
    date = "2026-04-23";
  };
  projects-yazi = {
    pname = "projects-yazi";
    version = "198c2ba30e4916ca275d2a08bd329fcf32735866";
    src = fetchFromGitHub {
      owner = "MasouShizuka";
      repo = "projects.yazi";
      rev = "198c2ba30e4916ca275d2a08bd329fcf32735866";
      fetchSubmodules = false;
      sha256 = "sha256-Grvtx+N1DpdpMaVuDwaHu3S7zu6pQtmu1twvFIowbLM=";
    };
    date = "2026-02-15";
  };
  shuorenhua = {
    pname = "shuorenhua";
    version = "8356a4f9190c5154820f10c6b372a90a1b92e600";
    src = fetchFromGitHub {
      owner = "shelken";
      repo = "shuorenhua";
      rev = "8356a4f9190c5154820f10c6b372a90a1b92e600";
      fetchSubmodules = false;
      sha256 = "sha256-SOyC+kEMySnv618ej9DK+HW9n2DQjkiP3AeeCeWRVmo=";
    };
    date = "2026-04-24";
  };
  software-design-philosophy-skill = {
    pname = "software-design-philosophy-skill";
    version = "e55ac385e89913a6d53c7da460d080982d32ea03";
    src = fetchFromGitHub {
      owner = "shelken";
      repo = "software-design-philosophy-skill";
      rev = "e55ac385e89913a6d53c7da460d080982d32ea03";
      fetchSubmodules = false;
      sha256 = "sha256-S6HF8QJ12UlpMDvbH8R7q3BSO6RBID3vNiQK4ib6bes=";
    };
    date = "2026-03-11";
  };
  taches-cc-resources = {
    pname = "taches-cc-resources";
    version = "1757615b99ab789a72ff2d02e9f6112af2a15c04";
    src = fetchFromGitHub {
      owner = "glittercowboy";
      repo = "taches-cc-resources";
      rev = "1757615b99ab789a72ff2d02e9f6112af2a15c04";
      fetchSubmodules = false;
      sha256 = "sha256-wWFJBd0AIIPYRWUG6LEFlKHpbpBQw4N2+7fX9BmjL6g=";
    };
    date = "2026-04-01";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "ac82af3e10f9a32cecd9f87ac64b3f9de7c7aea7";
      fetchSubmodules = false;
      sha256 = "sha256-svc7I2E+tVMEUWUvIS6i3oTGfLq13eaI61T0c1MQ8qQ=";
    };
    date = "2026-04-23";
  };
  zjstatus = {
    pname = "zjstatus";
    version = "v0.23.0";
    src = fetchurl {
      url = "https://github.com/dj95/zjstatus/releases/download/v0.23.0/zjstatus.wasm";
      sha256 = "sha256-4AaQEiNSQjnbYYAh5MxdF/gtxL+uVDKJW6QfA/E4Yf8=";
    };
  };
}
