# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  ai-coding-principles = {
    pname = "ai-coding-principles";
    version = "27db986fd2790ad1a1818a7f1b2c5d91b3843b8e";
    src = fetchFromGitHub {
      owner = "shelken";
      repo = "ai-coding-principles";
      rev = "27db986fd2790ad1a1818a7f1b2c5d91b3843b8e";
      fetchSubmodules = false;
      sha256 = "sha256-fkaO77jOmg9q3jEZe64SWgNWb2PUX9C1KvRDg4H+w8Y=";
    };
    date = "2026-03-26";
  };
  ai-design-skills = {
    pname = "ai-design-skills";
    version = "1c1e97cb9878e236552c772092dda7adcdddbcb2";
    src = fetchFromGitHub {
      owner = "elayadesign";
      repo = "ai-design-skills";
      rev = "1c1e97cb9878e236552c772092dda7adcdddbcb2";
      fetchSubmodules = false;
      sha256 = "sha256-Vscb+Cd6HnUk5222xIrJZ5q/cTqir5lhPWQ+RLAQ8d4=";
    };
    date = "2026-07-29";
  };
  andrej-karpathy-skills = {
    pname = "andrej-karpathy-skills";
    version = "2c606141936f1eeef17fa3043a72095b4765b9c2";
    src = fetchFromGitHub {
      owner = "forrestchang";
      repo = "andrej-karpathy-skills";
      rev = "2c606141936f1eeef17fa3043a72095b4765b9c2";
      fetchSubmodules = false;
      sha256 = "sha256-4z/wRdYH7UXRzF8RJU0sw8xbpx0BW/7CBv5sVEC2knY=";
    };
    date = "2026-04-20";
  };
  ast-grep-agent-skill = {
    pname = "ast-grep-agent-skill";
    version = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "agent-skill";
      rev = "c2a9bc154f4ffe08b25d28d5e852dfac8c0d0d8a";
      fetchSubmodules = false;
      sha256 = "sha256-awochSE2OupbsmaGx0xc7wHf0ovVMSdtHv4gZAGWOus=";
    };
    date = "2026-07-03";
  };
  emilkowalski-skills = {
    pname = "emilkowalski-skills";
    version = "de33dbed000212b54400a33767d1e4d03654db2a";
    src = fetchFromGitHub {
      owner = "emilkowalski";
      repo = "skills";
      rev = "de33dbed000212b54400a33767d1e4d03654db2a";
      fetchSubmodules = false;
      sha256 = "sha256-ABUbg0Ps28qMZ410msWmwDAhvIQi5qNAL1WkLbw5YA8=";
    };
    date = "2026-08-05";
  };
  impeccable = {
    pname = "impeccable";
    version = "ae5e95101a6979e7f7973a4ff57680b3c7adc1ec";
    src = fetchFromGitHub {
      owner = "pbakaus";
      repo = "impeccable";
      rev = "ae5e95101a6979e7f7973a4ff57680b3c7adc1ec";
      fetchSubmodules = false;
      sha256 = "sha256-efbINjnGr0WneoroeiqTWVeiiqEdiGVeesLBs3aM+ew=";
    };
    date = "2026-08-04";
  };
  kitty-icon = {
    pname = "kitty-icon";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "DinkDonk";
      repo = "kitty-icon";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-q5wNdFRMvQDx3DlO7zdy/xPJbqcNlm4iVKaBwjxlSMs=";
    };
  };
  llamaparse-agent-skills = {
    pname = "llamaparse-agent-skills";
    version = "2dcef7c62417bd2ec4671fce4621bb1e8cce48d0";
    src = fetchFromGitHub {
      owner = "run-llama";
      repo = "llamaparse-agent-skills";
      rev = "2dcef7c62417bd2ec4671fce4621bb1e8cce48d0";
      fetchSubmodules = false;
      sha256 = "sha256-KzYcArVClk1mUBYLM/EmU3+rKzAHtpHRLAFVY1LbtKQ=";
    };
    date = "2026-07-03";
  };
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "8b36d4fb2635b3c21998dcd8144439c9e5ba7302";
    src = fetchFromGitHub {
      owner = "mattpocock";
      repo = "skills";
      rev = "8b36d4fb2635b3c21998dcd8144439c9e5ba7302";
      fetchSubmodules = false;
      sha256 = "sha256-RwFJdrPnyieN65QrwSfABRuBzMdyUIf/qoJ1M8zLLps=";
    };
    date = "2026-08-05";
  };
  projects-yazi = {
    pname = "projects-yazi";
    version = "22a4006f531b7c8e71704f64e48feed659164104";
    src = fetchFromGitHub {
      owner = "MasouShizuka";
      repo = "projects.yazi";
      rev = "22a4006f531b7c8e71704f64e48feed659164104";
      fetchSubmodules = false;
      sha256 = "sha256-J3MM4Fc3+6P84OrC4DWqchSPbEOuzhEeO8rzNYXSZXQ=";
    };
    date = "2026-07-11";
  };
  redesign-skill = {
    pname = "redesign-skill";
    version = "64627f6ebe7a7a2f17c0affe4fe5838e2d46a876";
    src = fetchFromGitHub {
      owner = "elayadesign";
      repo = "redesign-skill";
      rev = "64627f6ebe7a7a2f17c0affe4fe5838e2d46a876";
      fetchSubmodules = false;
      sha256 = "sha256-en6PdayGgqm28R/DvchzCyjSi4pkyM8/GHfKQL8dy2M=";
    };
    date = "2026-07-20";
  };
  taches-cc-resources = {
    pname = "taches-cc-resources";
    version = "1757615b99ab789a72ff2d02e9f6112af2a15c04";
    src = fetchFromGitHub {
      owner = "glittercowboy";
      repo = "taches-cc-resources";
      rev = "1757615b99ab789a72ff2d02e9f6112af2a15c04";
      fetchSubmodules = false;
      sha256 = "sha256-wWFJBd0AIIPYRWUG6LEFlKHpbpBQw4N2+7fX9BmjL6g=";
    };
    date = "2026-04-01";
  };
  taste-skill = {
    pname = "taste-skill";
    version = "e988add20dab0fa97d7a76781c48961c8184288e";
    src = fetchFromGitHub {
      owner = "Leonxlnx";
      repo = "taste-skill";
      rev = "e988add20dab0fa97d7a76781c48961c8184288e";
      fetchSubmodules = false;
      sha256 = "sha256-Zt3fC8/63ZHcsFLjNR6/zNykrVkT0QV3SmmCi1dlnJA=";
    };
    date = "2026-07-23";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "b9598e6cbe721aa29bf64836ce314584cfeb58fc";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "b9598e6cbe721aa29bf64836ce314584cfeb58fc";
      fetchSubmodules = false;
      sha256 = "sha256-mrQq3r1dzM3DmEyke8CvSLbacgLQ4tNiqYHCOyXaqp0=";
    };
    date = "2026-08-03";
  };
  zjstatus = {
    pname = "zjstatus";
    version = "v0.24.0";
    src = fetchurl {
      url = "https://github.com/dj95/zjstatus/releases/download/v0.24.0/zjstatus.wasm";
      sha256 = "sha256-HM7ezh3tYs8+IJvmkM3TnKb7noIo7XGpUfZQf5lWZps=";
    };
  };
}
