#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Assign apps to specific spaces
# yabai -m rule --add app="^Arc$" space=1

yabai -m rule --add app="^OpenAI Translator$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Screen Sharing$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^Settings$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add title="Software Update" manage=off
yabai -m rule --add app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="System Information" title="System Information" manage=off
yabai -m rule --add app="Easydict" manage=off
yabai -m rule --add app="WeChat" title!="WeChat \(Chats\)" manage=off
yabai -m rule --add app="Lark Helper" manage=off # 飞书

# 画中画 PIP 
yabai -m rule --add app="^Arc$" subrole="^AXSystemDialog$" manage=off

# JetBrains
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA)$'
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].+" manage=on 
# yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on

# float system preferences
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^Archive Utility$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# 窗口聚焦闪烁
# yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"
# sip 需要关闭
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# boarders 该路径在x86上可能不行
/opt/homebrew/bin/borders active_color=0xffCAD3F5 inactive_color=0xbb282E44 hidpi=on width=3.0 &

echo "yabai configuration loaded.."
