hs.hotkey.bind({"alt"}, "B", function()
  hs.application.launchOrFocus("Helium")
end)
hs.hotkey.bind({"alt"}, "C", function()
  hs.application.launchOrFocus("Visual Studio Code")
end)
hs.hotkey.bind({"alt"}, "F", function()
  hs.application.launchOrFocus("Finder")
end)
hs.hotkey.bind({"alt"}, "K", function()
  hs.application.launchOrFocus("Kitty")
end)
hs.hotkey.bind({"alt"}, "W", function()
  hs.application.launchOrFocus("WeChat")
end)
return {}