"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio        = [2, 7, 7]
show_hidden  = true
show_symlink = true

# markdown preview
[[plugin.prepend_previewers]]
url  = "*.md"
run  = "piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark \"$1\""

[preview]
tab_size = 3
