{
  username,
  pkgs,
  ...
}: {
  nix.settings.trusted-users = [username];

  users.groups = {
    "${username}" = {};
    docker = {};
  };
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$6$fp3uxFyqFlkw/uSt$T4ji2Vq6CH/71hQkwTsxgj56iVKP.QF.NFst71D8wNDF5ubazRYqkmr30lNJfPRl3KpM1MOwHwC8Zjsuo5LOx0";
    home = "/home/${username}";
    isNormalUser = true;
    description = username;
    shell = pkgs.zsh;
    extraGroups = [
      username
      "users"
      "networkmanager"
      "wheel"
      "docker"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK1/TnqUWbdQgCcF1mXsgdMumR7EKGpyKn19SHzhFBuY shelken@yuuko"
    ];
  };

  # 默认shell=zsh需要此
  programs.zsh.enable = true;

  # DO NOT promote the specified user to input password for `nix-store` and `nix-copy-closure`
  security.sudo.extraRules = [
    {
      users = [username];
      commands = [
        {
          command = "/run/current-system/sw/bin/nix-store";
          options = ["NOPASSWD"];
        }
        {
          command = "/run/current-system/sw/bin/nix-copy-closure";
          options = ["NOPASSWD"];
        }
      ];
    }
  ];
}
