# my config for kitty (BACKUP ONLY)
# The actual effective config is managed via Nix: home/base/gui/kitty/default.nix
# This file is kept in sync for reference purposes only.

allow_remote_control no

font_family JetBrainsMono Nerd Font Mono
font_size   18.0
cursor_trail 3

background_opacity 0.88
background_blur 64

macos_show_window_title_in none
hide_window_decorations titlebar-only
window_padding_width 3 5 1 5

tab_bar_edge        bottom
tab_bar_style       powerline
tab_powerline_style slanted
tab_bar_min_tabs    2
tab_title_template  {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

macos_option_as_alt yes
enabled_layouts splits,stack

#-- keymap
map cmd+ctrl+,      load_config_file

map cmd+t           new_tab
map cmd+w           close_tab

map cmd+shift+m     toggle_maximized
map cmd+shift+l     next_layout
map cmd+shift+f     show_scrollback

map cmd+c           copy_to_clipboard
map cmd+v           paste_from_clipboard
map cmd+shift+v     paste_from_selection

map cmd+enter       launch --location=hsplit --cwd=current
map cmd+shift+enter launch --location=vsplit --cwd=current

map cmd+[           previous_tab
map cmd+]           next_tab

map cmd+ctrl+up     move_window up
map cmd+ctrl+left   move_window left
map cmd+ctrl+right  move_window right
map cmd+ctrl+down   move_window down

map cmd+left        neighboring_window left
map cmd+right       neighboring_window right
map cmd+up          neighboring_window up
map cmd+down        neighboring_window down

map alt+shift+left  resize_window narrower 2
map alt+shift+right resize_window wider 2
map alt+shift+up    resize_window taller 2
map alt+shift+down  resize_window shorter 2

#--

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
