name: Sync nvfetcher Sources

on:
  schedule:
    - cron: "0 20 * * *" # Daily 04:00 AM Asia/Shanghai
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nvfetcher-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Run nvfetcher
        run: |
          nix develop --command nvfetcher -c nvfetcher.toml -o _sources

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(nvfetcher): sync _sources generated files"
          file_pattern: "_sources/*"
